Feature/authentication and authorization
M-HAMMAD-HAZELSOFT/webapi pull request #4
Opened 2023-06-07 11:01 UTC by M-HAMMAD-HAZELSOFT

2023-06-07 13:43 UTC, HassanMustafaHazel requested changes

2023-06-07 13:43 UTC, HassanMustafaHazel commented on Program.cs
> +
again dependency injection.

2023-06-07 13:43 UTC, HassanMustafaHazel commented on Services/Authorization/AuthService.cs
> +                Encoding.UTF8.GetBytes(_configuration.GetSection("AppSettings:Token").Value)
why magic strings are present.

2023-06-09 10:49 UTC, HassanMustafaHazel requested changes

2023-06-09 10:49 UTC, HassanMustafaHazel commented on Services/Authorization/AuthService.cs
> +                    await _signInManager.SignInAsync(newUser, isPersistent: false);
why are you trying to login the user after creating it?

2023-06-09 11:00 UTC, M-HAMMAD-HAZELSOFT commented on Services/Authorization/AuthService.cs
> +                    await _signInManager.SignInAsync(newUser, isPersistent: false);
removed it. I added it by mistake.

2023-06-12 06:20 UTC, merged